apiVersion: v1
kind: Service
metadata:
  name: private-api-service
  namespace: private
spec:
  type: ClusterIP
  selector:
    app: private-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
